# GitHub Actions workflow — Generic, robust: publish a Python package to PyPI on tag, release, or manual dispatch.

name: Publish Python Package to PyPI

on:
  push:
    tags:
      - 'v*'                         # Trigger on version tags (e.g., v1.2.3)
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'setup.cfg'
      - 'setup.py'
      - '.github/workflows/**'
  release:
    types:
      - published                     # Trigger when a GitHub Release is published
  workflow_dispatch:                  # Allow manual runs

concurrency:
  group: publish-pypi-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  publish:
    if: >
      startsWith(github.ref, 'refs/tags/') ||
      github.event_name == 'release' ||
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install build & publish tools
        run: python -m pip install --upgrade pip build twine setuptools wheel

      - name: Build distributions
        run: python -m build --sdist --wheel

      - name: List dist files
        run: ls -la dist || true

      - name: Publish to PyPI
        env:
          # Recommended: create a PyPI API token and store it in the repo/org secret PYPI_API_TOKEN.
          # Twine uses username="__token__" and password=<api-token>.
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          # Optional legacy fallback (uncomment if you prefer username/password secrets):
          # TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          # TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          if [ ! -d "dist" ] || [ -z "$(ls -A dist 2>/dev/null)" ]; then
            echo "No artifacts found in dist/; aborting upload." >&2
            exit 1
          fi
          python -m twine upload dist/*